### ISSUE TITLE
Rename repo name for better SEO

### ISSUE THREAD

**Issue by kezhenxu94** [SkyAPM/mini-program-monitor#2]
"xx 小程序" such as "微信小程序", "支付宝小程序", "钉钉小程序" are translated as "xxx Mini Program" in their official documentations, I'd suggest rename the repo to "mini-program-monitor" and add Chinese description for better SEO.

https://developers.weixin.qq.com/miniprogram/en/dev/framework/
https://global.alipay.com/docs/ac/tool/miniapp

**Comment by wu-sheng** [comment]
I am fine with the renaming. @Jtrust @Fine0830 Make sense?

**Comment by Jtrust** [comment]
I think it's a good idea.

**Comment by Fine0830** [comment]
Make sense to me.

**Comment by wu-sheng** [comment]
Rename completed, https://github.com/SkyAPM/mini-program-monitor
